export const PRODUCT_OPTIONS = [
    "Comb-On Hair Color Cream 200ml Black",
    "Comb-On Hair Color Cream 200ml chestnut brown",
    "Comb-On Hair Color Cream 200ml dark brown",
    "hair color comb black",
    "hair color comb chestnut brown",
    "hair color comb dark brown",
    "refill black",
    "refill chestnut brown",
    "refill dark brown",
    "black+refill black",
    "black+refill chestnut brown",
    "black+refill dark brown",
    "chestnut brown+refill black",
    "chestnut brown+refill chestnut brown",
    "chestnut brown+refill dark brown",
    "dark brown+refill black",
    "dark brown+refill chestnut brown",
    "dark brown+refill dark brown",
    "500ml shampoo balck",
    "500ml shampoo dark brown",
    "500ml shampoo red brown",
    "500ml shampoo balck*2",
    "500ml shampoo dark brown*2",
    "500ml shampoo red brown*2",
    "500ml shampoo balck+dark brown",
    "500ml shampoo balck+red brown",
    "500ml shampoo dark brown+red brown",
    "Hair Shadow Natural Black",
    "Hair Shadow Light Brown",
    "Hair Shadow Dark Brown",
    "Hair Shadow Dark Coffee",
    "Hair Shadow Natural Black*2",
    "Hair Shadow Light Brown*2",
    "Hair Shadow Dark Brown*2",
    "Hair Shadow Dark Coffee*2",
    "Hair Shadow Natural Black+Light Brown",
    "Hair Shadow Natural Black+Dark Brown",
    "Hair Shadow Natural Black+Dark Coffee",
    "Hair Shadow Light Brown+Dark Brown",
    "Hair Shadow Light Brown+Dark Coffee",
    "Hair Shadow Dark Brown+Dark Coffee",
    "1 sachet black",
    "1 sache dark brown",
    "3 sache dark brown",
    "5 sachet black",
    "5 sache dark brown",
    "3 dark brown + 2 black",
    "1 box shampoo black",
    "1 box shampoo dark brown",
    "hair color comb black+Conditioner",
    "hair color comb chestnut brown+Conditioner",
    "hair color comb dark brown+Conditioner",
    "hair conditioner",
    "hair conditioner*2",
    "hair oil",
    "hair oil*2",
    "hair color comb black+hair oil",
    "hair color comb chestnut brown+hair oil",
    "hair color comb dark brown+hair oil"
];
